[tool.poetry]
name = "dl-from-scratch"
version = "0.1.0"
description = ""
authors = ["jeongmin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
